trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: Bash@3
  displayName: Install dependencies
  inputs:
    targetType: 'inline'
    script: |
      sudo apt-get update 
      sudo apt-get install lua5.2

- task: Bash@3  
  displayName: Compile Source
  inputs:
    targetType: 'inline'
    script: |
      ./bin/build.sh

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.SourcesDirectory)/obj'
    artifact: 'betaflight-tx-lua-derdanu-b$(Build.BuildId)'
