trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: Bash@3
  displayName: Install dependencies
  inputs:
    targetType: 'inline'
    script: |
      sudo apt-get update 
      sudo apt-get install lua5.2

- task: Bash@3  
  displayName: Compile Source
  inputs:
    targetType: 'inline'
    script: |
      ./bin/build.sh

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)/obj'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/betalight-lua-derdanu-b$(Build.BuildId).zip'
    replaceExistingArchive: true
    
- task: AzureFileCopy@3
  inputs:
    SourcePath: '$(Build.ArtifactStagingDirectory)/betalight-lua-derdanu-b$(Build.BuildId).zip'
    azureSubscription: 'Microsoft Azure Internal Consumption(6e8fd20c-17b0-4457-bea7-d20b50f95c95)'
    Destination: 'AzureBlob'
    storage: 'derdanugithub'
    ContainerName: 'betaflight-tx-lua-derdanu'


- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.SourcesDirectory)/obj'
    artifact: 'betaflight-tx-lua-derdanu-b$(Build.BuildId)'
