# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'


- task: Install Lua
  inputs:
    targetType: 'inline'
    script: |
      apt-get update 
      apt-get install lua5.2

- task: Build Code
  inputs:
    targetType: 'inline'
    script: |
      ./bin/build.sh